In [2]:
import pandas as pd

# Leer archivos CSV y JSON con Pandas

La libreria Pandas esta enfocada en la manipulación y analísis de datos, una de sus particularidades es que nos permite leer archivos externos de tipo CSV, JSON, HTML, XML, y un largo etc. Y trabajar posteriormente con su contenido.

## CSV

Por sus siglas en ingles "**C**oma **S**epareted **V**alues", estos son archivos de formato abierto que representan los datos en formato de tablas, donde cada valor esta separado por comas (,) y cada separación corresponde a una columna.
<br>
Este es el formato más común para trabajar con datos en el mundo de Data Science.

In [6]:
files_path = '/home/pahoalapizco/anaconda3/curso-pandas-numpy/pandas/data_sources'

In [8]:
csv_path = f'{files_path}/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv'
csv_path

'/home/pahoalapizco/anaconda3/curso-pandas-numpy/pandas/data_sources/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv'

Al leer archivos CSV con pandas podemos trabajar con él en una estructura matricial.

In [14]:
df_books = pd.read_csv(csv_path)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

La función `read_csv` recibe como parámetro obligatorio la ruta del archivo que va a leer, pero también recibe otro parametros que son opcionales, algunos de ellos son los siguientes:

#### sep
En este parametro indicamos como estan separados los valores del archivo, pandas toma por default la coma (,) siendo este el más común, pero hay ocasiones que podemos encontrarnos un pipe (|) como delimitador de columnas, es en ese caso cuando debemos especificarlo.

In [13]:
df_books = pd.read_csv(csv_path, sep='|') # Al indicale un separador diferente al que lleva el archivo, la estructura que obtenemos cambia (no es la correcta).
df_books

      Name,Author,User Rating,Reviews,Price,Year,Genre
0    10-Day Green Smoothie Cleanse,JJ Smith,4.7,173...
1    11/22/63: A Novel,Stephen King,4.6,2052,22,201...
2    12 Rules for Life: An Antidote to Chaos,Jordan...
3    1984 (Signet Classics),George Orwell,4.7,21424...
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545  Wrecking Ball (Diary of a Wimpy Kid Book 14),J...
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

[550 rows x 1 columns]

#### header
Le indicamos que fila del archivo CSV contiene el encabezado. Por default, toma el 0.

In [19]:
df_books = pd.read_csv(csv_path, sep=',', header=2)
df_books

,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
0,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
1,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
2,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
3,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
4,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
...,...,...,...,...,...,...,...
543,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
544,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
545,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

### names
Lista de los nombres de las columnas del archivo (array de strings), si el archivo no lleva nombre de encabezados definidos o bien si queremos sobre escribir los ya existentes

In [21]:
df_books = pd.read_csv(csv_path, names=['Nombre', 'Autor', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])
df_books

,Nombre,Autor,User Rating,Reviews,Price,Year,Genre
0,Name,Author,User Rating,Reviews,Price,Year,Genre
1,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
2,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
3,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
4,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
...,...,...,...,...,...,...,...
546,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
550,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

[Documentación de read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

## JSON
Por sus siglas en ingles **J**ava**S**cript **O**bject **N**otation, es un archivo de datos semiestructurado, facil de leer por su formato de clave-valor.

In [23]:
json_path = f'{files_path}/HPCharactersDataRaw.json'

In [25]:
df_characters = pd.read_json(json_path)
df_characters

,Name,Link,Descr,Gender,Species/Race,Blood,School,Profession
0,Mrs. Abbott,https://www.hp-lexicon.org/character/abbott-fa...,"Mrs. Abbott was the mother of Hannah Abbott, a...",Female,Witch,Muggle-born,Unknown,Unknown
1,Hannah Abbott,https://www.hp-lexicon.org/character/abbott-fa...,Hannah Abbott is a Hufflepuff student in Harry...,Female,Witch,Half-blood,Hogwarts - Hufflepuff,Landlady of the Leaky Cauldron
2,Abel Treetops,https://www.hp-lexicon.org/character/abel-tree...,Abel Treetops was a wizard from Cincinnati who...,Male,Wizard,Unknown,Unknown,Unknown
3,Euan Abercrombie,https://www.hp-lexicon.org/character/abercromb...,Euan Abercrombie was a small boy with prominen...,Male,Wizard,Unknown,Hogwarts - Gryffindor,Unknown
4,Aberforth Dumbledore,https://www.hp-lexicon.org/character/dumbledor...,"Aberforth Dumbledore was a tall, thin, grumpy-...",Male,Wizard,Half-blood,Hogwarts - Student,Barman
...,...,...,...,...,...,...,...,...
1935,Georgi Zdravko,https://www.hp-lexicon.org/character/georgi-zd...,Georgi Zdravko played Keeper for the Bulgarian...,Male,Wizard,Unknown,Unknown,Quidditch player (Seeker)
1936,Zograf,https://www.hp-lexicon.org/character/zograf/,Zograf played Keeper for the Bulgarian Nationa...,NaN,Wizard,Unknown,Unknown,Quidditch player (Keeper)
1937,Zonko,https://www.hp-lexicon.org/character/zonko/,Founder(?) of Zonko’s Joke Shop. Possibly a re...,NaN,Unknown,Unknown,Unknown,Unknown
1938,Valentina Vázquez,https://www.hp-lexicon.org/character/valentina...,Valentina Vázquez was President of the Argenti...,Female,Witch,Unknown,Unknown,President of the Argentinian Council of Magic
1939,Zygmunt Budge,https://www.hp-lexicon.org/character/zygmunt-b...,Zygmunt Budge is considered to be one of the m...,Male,Wizard,Unknown,Hogwarts - Student,"Potions Master, Potioneer, Inventor, Author"

Al igual que con los archivos CSV con los archivos JSON pandas nos permite trabajar con ellos en una estructura matricial, tomando como nombres de columnas las claves/llaves del documento.
<br>
También podemos verlo y trabajar con el en su formato raw, sin embargo esa forma de trabajarlo no es la más común en Data Science.

In [26]:
df_characters = pd.read_json(json_path, typ='Series')
df_characters

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

[Documentación de read_json](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)